import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:dailytask/common/daily_todo.dart';
import 'dart:core';

class DataInFireStore {
  static Future<List<DailyTodo>> getAllEntries(String collection, String email) async {
    var collectionReference = FirebaseFirestore.instance.collection(collection);
    var querySnapshot = await collectionReference.where('email', isEqualTo: email).get();

    List<DailyTodo> dailyTodos = querySnapshot.docs.map((doc) {
      return DailyTodo(
        id : doc.id,
        task : doc.data()['task'],
        //id외의 data는 doc.data()['명칭']을 사용해야 data를 가져올 수 있다.
        email : email,
        date: (doc.data()['date'] as Timestamp).toDate(),
      );
    }).toList();

    return dailyTodos;
  }

  static Future<DailyTodo> addEntryWithAutogeneratedId(String collection, DailyTodo todo) async {
    var collectionReference = FirebaseFirestore.instance.collection(collection);
    var docRef = await collectionReference.add(todo.toMap());

    DailyTodo newTodo = DailyTodo(
      id: docRef.id,
      task: todo.task,
      email: todo.email,
      date: todo.date,
    );
    return newTodo;
  }
}

